name: iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.4

    - name: Build Xcode Project
      run: |
        xcodebuild -scheme CaBot-User -sdk iphonesimulator -configuration Debug build
        xcodebuild -scheme CaBot-Attend -sdk iphonesimulator -configuration Debug build
